[build]
  publish = "public"
  command = "hugo --minify --gc"
  
[build.environment]
  HUGO_VERSION = "0.87.0"
  HUGO_BASEURL = "/"

[[headers]]
  for = "/*" # This defines which paths this specific [[headers]] block will cover.

[headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  X-Content-Type-Options = "nosniff" # THIS IS NEW
  Content-Security-Policy = "form-action https:"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Strict-Transport-Security = "max-age=2592000"
  #Feature-Policy = "vibrate 'none'; geolocation 'none'; midi 'none'; notifications 'none'; push 'none'; sync-xhr 'none'; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; speaker 'none'; vibrate 'none'; fullscreen 'none'; payment 'none'"
  Permissions-Policy = "vibrate=(), geolocation=(), midi=(), notifications=(), push=(), sync-xhr=(), microphone=(), camera=(), magnetometer=(), gyroscope=(), speaker=(), vibrate=(), fullscreen=('self'), payment=()"
